/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import Normal_class.drug ;
import Normal_class.Placeorder;

import java.util.*;

import javax.swing.JOptionPane;

/**
 *
 * @author Mohamed Khaled
 */
public class Place_Order extends javax.swing.JFrame {
public ArrayList<Placeorder> orderItems = Placeorder.getorders();
int  totalSales =0;
    /**
     * Creates new form Place_Order
     */
    public Place_Order() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Add_to_bill = new javax.swing.JButton();
        paymentbill = new javax.swing.JButton();
        iddrug = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID Drug");

        Add_to_bill.setText("Add ");
        Add_to_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_to_billActionPerformed(evt);
            }
        });

        paymentbill.setText("Payment Bill ");
        paymentbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentbillActionPerformed(evt);
            }
        });

        iddrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iddrugActionPerformed(evt);
            }
        });

        jLabel2.setText("Quantity");

        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iddrug, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addComponent(Add_to_bill)
                        .addGap(62, 62, 62)
                        .addComponent(paymentbill, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(iddrug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add_to_bill)
                    .addComponent(paymentbill))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_to_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_to_billActionPerformed
        // TODO add your handling code here:
        int drug_id = Integer.parseInt(iddrug.getText());
        int quantit = Integer.parseInt(quantity.getText());
    
        ArrayList<drug> drugs = drug.getDrugs();
        boolean drugFound = false;
    
        for (drug d : drugs) {
            if (d.getDrugID() == drug_id) {
                drugFound = true;
                double finalprice = d.getprice();
            
            if (d.getDrugType().equals("cosmetics")) {
                finalprice *= 1.2;
            }
            
            if (d.getDrugType().equals("prescription drugs")) {
                String hasPrescription = JOptionPane.showInputDialog("This drug requires a prescription. Do you have one?");
                if (!"yes".equalsIgnoreCase(hasPrescription)) {
                    JOptionPane.showMessageDialog(null, "Cannot place the order without a prescription.");
                    return;
                }
            }
            
            if (d.getquantity() >= quantit) {
                d.setquantity(d.getquantity() - quantit);
                double orderTotal = finalprice * quantit;
                totalSales += orderTotal;
                orderItems.add(new Placeorder(d, quantit, orderTotal));
                JOptionPane.showMessageDialog(null, String.format("Order placed successfully"));
                return;
            } else {
                JOptionPane.showMessageDialog(null, "Insufficient quantity available.");
                return;
            }
        }
    }
    
    if (!drugFound) {
        JOptionPane.showMessageDialog(null, "Drug not found.");
    }

        
        
        
       

               
      
        
    }//GEN-LAST:event_Add_to_billActionPerformed

    private void paymentbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentbillActionPerformed

    StringBuilder billDetails = new StringBuilder();
    billDetails.append("Bill Payment Details:\n");

    for (Placeorder item : orderItems) {
       billDetails.append("Drug: " + item.getDrug().getDrugName() +
                     ", Quantity: " + item.getQuantity() +
                     ", Cost: $" +  item.getTotalCost() + "\n");
             
    }

    billDetails.append(String.format("Total Sales: "+ totalSales)); 
    JOptionPane.showMessageDialog(null, billDetails.toString());
    }//GEN-LAST:event_paymentbillActionPerformed

    private void iddrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iddrugActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_iddrugActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Place_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Place_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Place_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Place_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Place_Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_to_bill;
    private javax.swing.JTextField iddrug;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton paymentbill;
    private javax.swing.JTextField quantity;
    // End of variables declaration//GEN-END:variables
}
